name: FAST-VQA-B-Refactor-1*4
num_epochs: 100
l_num_epochs: 0
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 12
num_workers: 1

wandb:
  project_name: VQA_Experiments_2022

data:
  val-aigc_video:
    type: FusionDataset
    args:
      phase: test
      anno_file: /home/sunwei/code/VQA/RQ-VQA/data/test_data.csv
      data_prefix: /data/sunwei_data/ntire_video/test
      sample_types:
        fragments:
          fragments_h: 7
          fragments_w: 7
          fsize_h: 32
          fsize_w: 32
          aligned: 32
          clip_len: 32
          frame_interval: 2
          num_clips: 4

model:
  type: DiViDeAddEvaluator
  args:
    backbone:
      fragments:
        checkpoint: false
        pretrained:
    backbone_size: swin_tiny_grpb
    backbone_preserve_keys: fragments
    divide_head: false
    vqa_head:
      in_channels: 768
      hidden_channels: 64

optimizer:
  lr: !!float 1e-3
  backbone_lr_mult: !!float 1e-1
  wd: 0.05

test_load_path: /home/sunwei/code/VQA/RQ-VQA/ckpts/FAST_VQA_B_1_4.pth
